version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: anfw-localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,lambda,iam,cloudformation,logs,events,sns,sqs,ec2,networkfirewall
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - anfw-local

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: anfw-dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
    depends_on:
      - localstack
    networks:
      - anfw-local

networks:
  anfw-local:
    driver: bridge
